# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Infoworks2raster
                                 A QGIS plugin
 Rasteriza resultados de Infoworks ICM
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-11-18
        copyright            : (C) 2023 by Jhon E. Chahua Janampa
        email                : chahua.evar@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Infoworks2raster class from file Infoworks2raster.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Infoworks2raster import Infoworks2raster
    return Infoworks2raster(iface)
